spring:
  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: ru.vicsergeev.NotificationService.dto,com.vicsergeev.SpringHW.dto
            type:
              mapping: com.vicsergeev.SpringHW.dto.UserEventDTO:ru.vicsergeev.NotificationService.dto.UserEventDTO
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      type: single
      missing-topics-fatal: false
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 561b12b42a574e
    password: 2b5ae7e6ab93fd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG